;/////////////////////////////////////////////////////////////////////////////////////////////////////////
;FILE: mod/armor.inc //////////////////////////////////////////////////////////////////////////////
;/////////////////////////////////////////////////////////////////////////////////////////////////////////
;Just so you know the choices available, here is part of Damage.h
;
;
;	"FORCE",
;	"CRUSH",	
;	"SLASH",
;	"PIERCE",
;	"SIEGE",
;	"STRUCTURAL",
;
;	"FLAME",
;	"FROST"
;	"HEALING",	
;	"UNRESISTABLE",	
;	"WATER",
;	"PENALTY",	
;	"FALLING",	
;	"TOPPLING",
;	"REFLECTED",
;	"PASSENGER",
;	"MAGIC",
;	"CHOP",
;	"HERO",
;	"SPECIALIST",
;	"URUK",
;	"HERO_RANGED",
;	"FLY_INTO",
;
;	"UNDEFINED",
;	"LOGICAL_FIRE",
;	"CAVALRY",
;	"CAVALRY_RANGED",
;	"POISON",
;
;	"SLASH", - Fighter Dmg
;	"CAVALRY" - Cavalry Dmg
;	"PIERCE",  - Archer Dmg
;	"SPECIALIST", - Pikeman Dmg
;
;
;


;//////////////////////MOD ARMORS///////////////////////////////////////////
