Behavior = CostModifierUpgrade ModuleTag_CostModifier
    LabelForPalantirString	= GUI:STRUCTURE_WALL_DISCOUNT
    StartsActive = Yes
    ObjectFilter			= ANY +MenFortress +DwarvenFortress +ElvenFortress +IsengardFortress +MordorFortress +WildFortress +AngmarFortress
    Percentage				= 25.00%
    Percentage				= 50.00%
;    Percentage				= 75.00%
;    Percentage				= 100.00%
;    Percentage				= 125.00% 
End
