;;,;; 2.02e Wyrm DoT Breath

;------------------------------------------------------------------------------
	DamageNugget															; A basic Nugget that just does damage
		Damage			= #MULTIPLY( WYRM_FIRE_DAMAGE .100 )
		Radius			= WYRM_FIRE_RADIUS
		DamageType		= FLAME
		DamageFXType	= FLAME
		DeathType		= BURNED
		DamageArc		= 45
		DamageMaxHeight = 20 ;;,;; 50												; We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
	End

	; To catch the units standing right on the point of the triangle.
	DamageNugget															; A basic Nugget that just does damage
		Damage			= #MULTIPLY( WYRM_FIRE_DAMAGE .100 )
		Radius			= 20
		DamageType		= FLAME
		DamageFXType	= FLAME
		DeathType		= BURNED
		DamageMaxHeight = 20 ;;,;; 50												; We won't hurt something far above us.  Birds fly at around 100
	End

;------------------------------------------------------------------------------
	DamageNugget															; A basic Nugget that just does damage
		Damage			= #MULTIPLY( WYRM_FIRE_DAMAGE .100 )
		Radius			= WYRM_FIRE_RADIUS
		DelayTime		= 200
		DamageType		= FLAME
		DamageFXType	= FLAME
		DeathType		= BURNED
		DamageArc		= 45
		DamageMaxHeight = 20 ;;,;; 50												; We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
	End

	; To catch the units standing right on the point of the triangle.
	DamageNugget															; A basic Nugget that just does damage
		Damage			= #MULTIPLY( WYRM_FIRE_DAMAGE .100 )
		Radius			= 20
		DelayTime		= 200
		DamageType		= FLAME
		DamageFXType	= FLAME
		DeathType		= BURNED
		DamageMaxHeight = 20 ;;,;; 50												; We won't hurt something far above us.  Birds fly at around 100
	End

;------------------------------------------------------------------------------
	DamageNugget															; A basic Nugget that just does damage
		Damage			= #MULTIPLY( WYRM_FIRE_DAMAGE .100 )
		Radius			= WYRM_FIRE_RADIUS
		DelayTime		= 400
		DamageType		= FLAME
		DamageFXType	= FLAME
		DeathType		= BURNED
		DamageArc		= 45
		DamageMaxHeight = 20 ;;,;; 50												; We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
	End

	; To catch the units standing right on the point of the triangle.
	DamageNugget															; A basic Nugget that just does damage
		Damage			= #MULTIPLY( WYRM_FIRE_DAMAGE .100 )
		Radius			= 20
		DelayTime		= 400
		DamageType		= FLAME
		DamageFXType	= FLAME
		DeathType		= BURNED
		DamageMaxHeight = 20 ;;,;; 50												; We won't hurt something far above us.  Birds fly at around 100
	End

;------------------------------------------------------------------------------
	DamageNugget															; A basic Nugget that just does damage
		Damage			= #MULTIPLY( WYRM_FIRE_DAMAGE .100 )
		Radius			= WYRM_FIRE_RADIUS
		DelayTime		= 600
		DamageType		= FLAME
		DamageFXType	= FLAME
		DeathType		= BURNED
		DamageArc		= 45
		DamageMaxHeight = 20 ;;,;; 50												; We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
	End

	; To catch the units standing right on the point of the triangle.
	DamageNugget															; A basic Nugget that just does damage
		Damage			= #MULTIPLY( WYRM_FIRE_DAMAGE .100 )
		Radius			= 20
		DelayTime		= 600
		DamageType		= FLAME
		DamageFXType	= FLAME
		DeathType		= BURNED
		DamageMaxHeight = 20 ;;,;; 50												; We won't hurt something far above us.  Birds fly at around 100
	End

;------------------------------------------------------------------------------
	DamageNugget															; A basic Nugget that just does damage
		Damage			= #MULTIPLY( WYRM_FIRE_DAMAGE .100 )
		Radius			= WYRM_FIRE_RADIUS
		DelayTime		= 800
		DamageType		= FLAME
		DamageFXType	= FLAME
		DeathType		= BURNED
		DamageArc		= 45
		DamageMaxHeight = 20 ;;,;; 50												; We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
	End

	; To catch the units standing right on the point of the triangle.
	DamageNugget															; A basic Nugget that just does damage
		Damage			= #MULTIPLY( WYRM_FIRE_DAMAGE .100 )
		Radius			= 20
		DelayTime		= 800
		DamageType		= FLAME
		DamageFXType	= FLAME
		DeathType		= BURNED
		DamageMaxHeight = 20 ;;,;; 50												; We won't hurt something far above us.  Birds fly at around 100
	End

;------------------------------------------------------------------------------
	DamageNugget															; A basic Nugget that just does damage
		Damage			= #MULTIPLY( WYRM_FIRE_DAMAGE .100 )
		Radius			= WYRM_FIRE_RADIUS
		DelayTime		= 1000
		DamageType		= FLAME
		DamageFXType	= FLAME
		DeathType		= BURNED
		DamageArc		= 45
		DamageMaxHeight = 20 ;;,;; 50												; We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
	End

	; To catch the units standing right on the point of the triangle.
	DamageNugget															; A basic Nugget that just does damage
		Damage			= #MULTIPLY( WYRM_FIRE_DAMAGE .100 )
		Radius			= 20
		DelayTime		= 1000
		DamageType		= FLAME
		DamageFXType	= FLAME
		DeathType		= BURNED
		DamageMaxHeight = 20 ;;,;; 50												; We won't hurt something far above us.  Birds fly at around 100
	End

;------------------------------------------------------------------------------
	DamageNugget															; A basic Nugget that just does damage
		Damage			= #MULTIPLY( WYRM_FIRE_DAMAGE .100 )
		Radius			= WYRM_FIRE_RADIUS
		DelayTime		= 1200
		DamageType		= FLAME
		DamageFXType	= FLAME
		DeathType		= BURNED
		DamageArc		= 45
		DamageMaxHeight = 20 ;;,;; 50												; We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
	End

	; To catch the units standing right on the point of the triangle.
	DamageNugget															; A basic Nugget that just does damage
		Damage			= #MULTIPLY( WYRM_FIRE_DAMAGE .100 )
		Radius			= 20
		DelayTime		= 1200
		DamageType		= FLAME
		DamageFXType	= FLAME
		DeathType		= BURNED
		DamageMaxHeight = 20 ;;,;; 50												; We won't hurt something far above us.  Birds fly at around 100
	End

;------------------------------------------------------------------------------
	DamageNugget															; A basic Nugget that just does damage
		Damage			= #MULTIPLY( WYRM_FIRE_DAMAGE .100 )
		Radius			= WYRM_FIRE_RADIUS
		DelayTime		= 1400
		DamageType		= FLAME
		DamageFXType	= FLAME
		DeathType		= BURNED
		DamageArc		= 45
		DamageMaxHeight = 20 ;;,;; 50												; We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
	End

	; To catch the units standing right on the point of the triangle.
	DamageNugget															; A basic Nugget that just does damage
		Damage			= #MULTIPLY( WYRM_FIRE_DAMAGE .100 )
		Radius			= 20
		DelayTime		= 1400
		DamageType		= FLAME
		DamageFXType	= FLAME
		DeathType		= BURNED
		DamageMaxHeight = 20 ;;,;; 50												; We won't hurt something far above us.  Birds fly at around 100
	End

;------------------------------------------------------------------------------
	DamageNugget															; A basic Nugget that just does damage
		Damage			= #MULTIPLY( WYRM_FIRE_DAMAGE .100 )
		Radius			= WYRM_FIRE_RADIUS
		DelayTime		= 1600
		DamageType		= FLAME
		DamageFXType	= FLAME
		DeathType		= BURNED
		DamageArc		= 45
		DamageMaxHeight = 20 ;;,;; 50												; We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
	End

	; To catch the units standing right on the point of the triangle.
	DamageNugget															; A basic Nugget that just does damage
		Damage			= #MULTIPLY( WYRM_FIRE_DAMAGE .100 )
		Radius			= 20
		DelayTime		= 1600
		DamageType		= FLAME
		DamageFXType	= FLAME
		DeathType		= BURNED
		DamageMaxHeight = 20 ;;,;; 50												; We won't hurt something far above us.  Birds fly at around 100
	End

;------------------------------------------------------------------------------
	DamageNugget															; A basic Nugget that just does damage
		Damage			= #MULTIPLY( WYRM_FIRE_DAMAGE .100 )
		Radius			= WYRM_FIRE_RADIUS
		DelayTime		= 1800
		DamageType		= FLAME
		DamageFXType	= FLAME
		DeathType		= BURNED
		DamageArc		= 45
		DamageMaxHeight = 20 ;;,;; 50												; We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
	End

	; To catch the units standing right on the point of the triangle.
	DamageNugget															; A basic Nugget that just does damage
		Damage			= #MULTIPLY( WYRM_FIRE_DAMAGE .100 )
		Radius			= 20
		DelayTime		= 1800
		DamageType		= FLAME
		DamageFXType	= FLAME
		DeathType		= BURNED
		DamageMaxHeight = 20 ;;,;; 50												; We won't hurt something far above us.  Birds fly at around 100
	End